#!/bin/sh

_lister() {
	body_content=$(curl -Ls "https://api.gh.pkgforge.dev/repos/AppImage/appimage.github.io/issues/$a" | jq -r '.body')
	wait
	exists=""
	if echo "$body_content" | grep -q "^Repository: https://github.com/"; then
		repo=$(echo "$body_content" | tr '>< ' '\n' | grep "https://github.com/" | sed "s#https://github.com/##g" | head -1)
		if [ -n "$repo" ]; then
			for script in ./AM/programs/x86_64/*; do
				if grep -q "$repo" "$script"; then
					exists=1
				fi
			done
			[ -z "$exists" ] && echo "$repo" && echo "$repo" >> list
		fi
	fi
}

ARGS=$(seq 6000 9516)
if [ ! -d ./AM/programs/x86_64 ]; then
	git clone https://github.com/ivan-hc/AM.git || exit 1
fi
wait

if [ -d ./AM/programs/x86_64 ]; then
	for a in $ARGS; do
		_lister
	done
	wait
	sort -u list > sources.txt
else
	echo "Directory not found" && exit 1
fi
